[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AtmosphericProfilesLibrary = "86bc3604-9858-485a-bdbe-831ec50de11d"
Breeze = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Breeze = "0.3.0"
